### ISSUE TITLE
part cooling fan is always open

### ISSUE THREAD

**Issue by SFRSKZ** [makerbase-mks/MKS-Robin-E3-E3D#1]
im using pa8 pin for part cooling fan but fan is always working. not responding to adjustments or gcodes.

**Comment by makerbase-mks** [comment]
Hi!
I want to confirm the following points:
First, your firmware is what version?
Secondly, when the motherboard is powered on, will the FAN controlled by PA8 flash or keep on?

**Comment by SFRSKZ** [comment]
marlin 2.0.1. i used your files, and changed some settings but there was nothing about fan.

**Comment by SFRSKZ** [comment]
![image](https://user-images.githubusercontent.com/52824173/78970303-addfb080-7b11-11ea-8dd1-f9677d8d9104.jpg)

red light is always on, not blinking.

**Comment by makerbase-mks** [comment]
Have you received the motherboard, is this the case with power on? If it is always on, it means that the transistor controlling the FAN has been broken down, which will cause the power to be on all the time without blinking.

**Comment by jvictor23br** [comment]
Mine has the same issue, the red light is allways on, but the cooler is always off. Just received like that. What can be done?

**Comment by danbrianwhite** [comment]
I have one of these too where part cooling fan is always on. The hotend fan is connected to the "fan" input.

Is this a software bug?
