### ISSUE TITLE
Firmware update stopped on "update 100%"

### ISSUE THREAD

**Issue by piontec** [makerbase-mks/MKS-Robin-E3-E3D#101]
I configured the latest marlin-bugfix2.0.x according to your instructions. My board is v1.1. The firmware compiled and started to flash successfully, but then it's stuck on "update 100%". After removing the card, the printer won't boot and is stuck with message "boot" on the screen. THe firmware file is deleted from the sdcard.

**Comment by mks-viva** [comment]
Hi! You need copy Robin_e3.bin file to TF card and insert board update it

**Comment by piontec** [comment]
Hey! Thank you, I missed that. What is the difference between `firmware.bin` and `Robin_e3.bin`? I'm trying to make your board work with https://github.com/KevinOConnor/klipper and I have the same problem there - I guess the solution is the same. Can you help me convert klipper's binary as well?

**Comment by mks-viva** [comment]
Robin_e3.bin file is obtained by transcoding using firmware.bin file, so, we need use Robin_e3.bin file update firmware and cann't use firmware.bin rename as Robin_e3.bin, this is unusable.

**Comment by piontec** [comment]
Yes, but how to transcode the file?

**Comment by mks-viva** [comment]
You can refer to marlin about transcode and i has upload this file.
[mks_robin_e3.zip](https://github.com/makerbase-mks/MKS-Robin-E3-E3D/files/6341338/mks_robin_e3.zip)
![image](https://user-images.githubusercontent.com/16629551/115352762-4fe8ad00-a1ea-11eb-80c6-fb8e2dafda2b.png)

**Comment by mks-viva** [comment]
You can refer to Klipper here about how to transcode: https://github.com/KevinOConnor/klipper/blob/master/scripts/update_mks_robin.py

**Comment by piontec** [comment]
Thanks for the info, but exactly this script doesn't work for me - when I flash `Robin_e3.bin` from it, the printer hangs like with non-encoded firmware :( Just to confirm: which bootloader size and serial ports should I use for klipper?

**Comment by spooky79** [comment]
I have the same problem, it comes to 100% and nothing is happening, I'm using visual studio code, any solution?

**Comment by mks-viva** [comment]
@piontec About MKS Robin E3 use kilpper firmware settigs: https://github.com/KevinOConnor/klipper/pull/3008
@spooky79 What firmware you using?

**Comment by piontec** [comment]
It doesn't work for me, see my marlin report here: https://github.com/KevinOConnor/klipper/issues/4219

**Comment by piontec** [comment]
It turned out to be klipper issue, it was silently crashing without any info in logs. Closing as invalid.

**Comment by thiagoedson** [comment]
= aqui

**Comment by fex42** [comment]
I also have the same problem with Klipper. My workaround was to get back to the tagged v0.10.0 version and flash this. After flashing the board, you can go back to git HEAD for the stuff running on the Raspberry Pi

**Comment by bulcke** [comment]
> I also have the same problem with Klipper. My workaround was to get back to the tagged v0.10.0 version and flash this. After flashing the board, you can go back to git HEAD for the Klipper stuff running on the Raspberry Pi

@fex42 where can I find said tagged version?
