### ISSUE TITLE
Updated firmware, Extruder motor not working. Robin E3D

### ISSUE THREAD

**Issue by NiceManiac** [makerbase-mks/MKS-Robin-E3-E3D#103]
Hello, i recently updated my firmware for supporting 3d touch and linear advance.

The 3D touch sensor works flawlessly but my extruder wont turn at all(not vie octoprint, not via lcd display).

Attached my config files.
[Marlin.zip](https://github.com/makerbase-mks/MKS-Robin-E3-E3D/files/6330687/Marlin.zip)

**Comment by mks-viva** [comment]
Hi! I want to know, what do you use to control the E axis.

**Comment by NiceManiac** [comment]
i actually found the issue to this problem, PREVENT_COLD_EXTRUSION is broke in this release, and even when setting the min temperature to 100 degrees and heating the hotend to 200 it blocks the extruder from moving.
