### ISSUE TITLE
MKS TS35 with mesh bed leveling

### ISSUE THREAD

**Issue by Hoffmorr** [makerbase-mks/MKS-Robin-E3-E3D#109]
I want to enable mesh bed leveling through the LCD.  Is that supported?  I get the error that the screen is not programmable when I try to compile the FW which makes me think I cannot do the mesh bed leveling through the MKSTS35?  Is there a version of FW i can install on the MKS TS35 that will allow changes to the menus or something?

**Comment by mks-viva** [comment]
MKS Robin E3/E3D have not support MKS TS35 display screen.
