### ISSUE TITLE
BTT mini 12864 v1 in E3D V1.1

### ISSUE THREAD

**Issue by kacharros** [makerbase-mks/MKS-Robin-E3-E3D#114]
Does anyone know instructions to install a mini BTT 12864 v1 on Robin E3D v1.1?
I uncomment FYSECT_MINI_12864_2_1 y NEOPIXEL_LED , it as the BTT instructions put it and it gives an error.

**Comment by mks-viva** [comment]
Hi! You need add it in ini file
custom_marlin.NEOPIXEL_LED = Adafruit NeoPixel=https://github.com/ellensp/Adafruit_NeoPixel
![image](https://user-images.githubusercontent.com/16629551/122207259-86823180-ced4-11eb-9c48-54c10d809050.png)

**Comment by mks-viva** [comment]
You can refer to https://github.com/MarlinFirmware/Marlin/pull/22368

**Comment by zhongxb** [comment]
> Hi! You need add it in ini file
> custom_marlin.NEOPIXEL_LED = Adafruit NeoPixel=https://github.com/ellensp/Adafruit_NeoPixel
> ![image](https://user-images.githubusercontent.com/16629551/122207259-86823180-ced4-11eb-9c48-54c10d809050.png)

this address is 404,  https://github.com/ellensp/Adafruit_NeoPixel.
