### ISSUE TITLE
List of all the displays available

### ISSUE THREAD

**Issue by logisk** [makerbase-mks/MKS-Robin-E3-E3D#119]
Is there a list available where I can see which LCD's are compatible to the different boards of mks?

For e.g the MKS Robin E3 V1.1?

**Comment by mks-viva** [comment]
LCD2004
LCD12864
MKS LCD12864B
MKS MINI12864 V1.x and V2.x
MKS MINI12864 V3 RGB backlights: https://github.com/makerbase-mks/MKS-MINI12864-V3
MKS TFT series
