### ISSUE TITLE
Z Axis not moving Robin E3 V1.0

### ISSUE THREAD

**Issue by zoppp** [makerbase-mks/MKS-Robin-E3-E3D#120]
I have a robin e3 with replaceable stepper driver and am having issues getting the z axis to move.  To test the steppers and drivers, I switched one of the z motors from being connected to the Z1 port to the X axis port and commanded the x axis to move which worked as expected: One z motor moved. I moved the z stepper driver to the x axis connected to the z motor and it worked as well so that leads me to believe that the stepper drivers and the motors are fine. The endstop status when running M119 is all open so the endstops are not preventing motion.

I have placed the jumpers on the board to run the drivers in UART mode with the 2209 drivers. Please help, is there a marlin configuration I am missing? 

I am running the board on 12v for a wanhao duplicator i3. Not connected to the screen. Everything on the printer is working with the robin e3 board except for the z1/z2 ports.

**Comment by mks-viva** [comment]
Hi! If you use MKS Robin E3/E3D V1.1 board, you need set #define MOTHERBOARD BOARD_MKS_ROBIN_E3_V1_1
