### ISSUE TITLE
BTT mini12864 compile fail，

### ISSUE THREAD

**Issue by zhongxb** [makerbase-mks/MKS-Robin-E3-E3D#127]
Hi! You need add it in ini file
custom_marlin.NEOPIXEL_LED = Adafruit NeoPixel=https://github.com/ellensp/Adafruit_NeoPixel
![image](https://user-images.githubusercontent.com/16629551/122207259-86823180-ced4-11eb-9c48-54c10d809050.png)

_Originally posted by @mks-viva in https://github.com/makerbase-mks/MKS-Robin-E3-E3D/issues/114#issuecomment-862281285_

can't find response with https://github.com/ellensp/Adafruit_NeoPixel

404 not found

**Comment by mks-viva** [comment]
You can refer to here https://github.com/MarlinFirmware/Marlin/pull/22368, the latest version marlinhas supported it

**Comment by mks-viva** [comment]
https://github.com/makerbase-mks/MKS-Robin-E3-E3D/wiki/FYSETC_BTT_MINI12864
