### ISSUE TITLE
Note for v1.1 users!!!If your Z motor CAN'T ROTATE, but only hold in place (enable).

### ISSUE THREAD

**Issue by ChangboBro** [makerbase-mks/MKS-Robin-E3-E3D#128]
If your board is version v1.1, You have to define your board as : #define MOTHERBOARD BOARD_MKS_ROBIN_E3D_V1_1 , 
NOT #define MOTHERBOARD BOARD_MKS_ROBIN_E3D . Or you will get problem at Z motor, cause v1.1's dir pin and step pin at z motor is different from v1.0.
It akes me one day to find problem... /(ㄒoㄒ)/~~

**Comment by mks-viva** [comment]
OK! I will update it on wiki.

**Comment by ChangboBro** [comment]
> OK! I will update it on wiki.

Thx!

**Comment by mks-viva** [comment]
![image](https://user-images.githubusercontent.com/16629551/128584421-8f641ace-deee-41a5-b50a-a6faf02d6eef.png)
