### ISSUE TITLE
Firmware differences - v1.0 vs v1.1

### ISSUE THREAD

**Issue by pauloeduardogodoy** [makerbase-mks/MKS-Robin-E3-E3D#131]
Hello.

I would like to better understand the differences, if any, between the 1.0 hardware firmware and the 1.1 hardware firmware.

Thanks.

**Comment by mks-viva** [comment]
![image](https://user-images.githubusercontent.com/16629551/129345528-a82d4d70-9ad8-4111-92b0-ad755f1bb8bc.png)

**Comment by pauloeduardogodoy** [comment]
So those changes are related to v1.0_003 to 1.1_003? Is that correct?

Here should I change those parameters in vanilla Marlin 2.0.9.1?

**Comment by mks-viva** [comment]
You only set board type: BOARD_MKS_ROBIN_E3_V1_1 or BOARD_MKS_ROBIN_E3D_V1_1
