### ISSUE TITLE
REPRAP_DISCOUNT_SMART_CONTROLLER

### ISSUE THREAD

**Issue by 131710cc** [makerbase-mks/MKS-Robin-E3-E3D#135]
![WhatsApp Image 2021-08-31 at 19 59 37](https://user-images.githubusercontent.com/89163113/131587698-f011ec0c-a8bc-4ad5-b201-4064634701c1.jpeg)
This is how is my lcd after connect to my e3d, with a sd or not, it do not show any character

**Comment by mks-viva** [comment]
Please provide your source code to me.

**Comment by mks-viva** [comment]
I has test it and it's will work. May be you need check your wiring and your lcd.
[Robin_e3.zip](https://github.com/makerbase-mks/MKS-Robin-E3-E3D/files/7119646/Robin_e3.zip)
![image](https://user-images.githubusercontent.com/16629551/132300761-c9802e3a-3fd2-4743-96cd-9401bba3c903.png)

**Comment by 131710cc** [comment]
Could you send me the correct way to wiring this lcd? cause it looks right in the picture.

**Comment by mks-viva** [comment]
Connect the EXP1 and EXP2 cable to the screen and to the motherboard if it still doesn't work this means you have to rotate the plug 180 degrees.
![image](https://user-images.githubusercontent.com/16629551/133017438-0e564294-d687-43ca-b3b5-bc4770f18d96.png)
