### ISSUE TITLE
STM32F103 / STM32F407 boards BOOT0 pin should have *jumper* (or button) to VDD 3v3

### ISSUE THREAD

**Issue by ag88** [makerbase-mks/MKS-Robin-E3-E3D#140]
STM32F103 / STM32F407 boards BOOT0 pin should have *jumper* (or button) to VDD 3v3, and the pin should be resistor to GND. 1k, 4.7k etc. or can jumper both sides 3V3, BOOT0, GND, so normal use jumper BOOT0, GND, program jumper 3V3, BOOT0

Your boards are quite good, but for many of your boards
e.g. Robin Nano V3
https://github.com/makerbase-mks/MKS-Robin-Nano-V3.X/blob/main/hardware/MKS%20Robin%20Nano%20V3.0_004/MKS%20Robin%20Nano%20V3.0_004%20SCH.pdf
Robin Nano V1.x
https://github.com/makerbase-mks/MKS-Robin-Nano-V1.X
Robin E3D
https://github.com/makerbase-mks/MKS-Robin-E3-E3D/blob/master/hardware/MKS%20Robin%20E3%20V1.1_004/MKS%20Robin%20E3%20V1.1_004%20SCH.pdf
https://github.com/makerbase-mks/MKS-Robin-Nano-V1.X/blob/master/hardware/MKS%20Robin%20Nano%20V1.3_002/MKS%20Robin%20Nano%20V1.3_002%20SCH.pdf

BOOT0 is tie to GND, this is not good. BOOT0 allows the use of UART to upload firmware on PA9 TX, PA10 RX for STM32F103. And for STM32F407 BOOT0 allows direct USB DFU firmware upload (no need extra boot loader or st-link). The procedure is set BOOT0, press reset, upload firmware.

So for STM32F103 (for STM32F407 as well) uart1 pins PA9, PA10 should be made available on headers. I think this is already ok.

**Comment by mks-viva** [comment]
MKS Robin Nano V3.X has same the issues, so, i will close this issues.
https://github.com/makerbase-mks/MKS-Robin-Nano-V3.X/issues/63
