### ISSUE TITLE
PINOUT BOARD_MKS_ROBIN_E3D_V1_1

### ISSUE THREAD

**Issue by pacocatech** [makerbase-mks/MKS-Robin-E3-E3D#150]
Hey guys,

My FAN ports burned and I want to switch to free ports on my E3D V1.1, can you tell me which pins are associated with the connectors: J6 and J5 ? 

![image](https://user-images.githubusercontent.com/70729684/144668037-06857aea-7c58-49ff-bca8-46a5a6003361.png)

**Comment by mks-viva** [comment]
J5, J6 is power out and the power form you vin.
