### ISSUE TITLE
I can't update .bin file

### ISSUE THREAD

**Issue by JordiKoki** [makerbase-mks/MKS-Robin-E3-E3D#2]
I am trying to update my new MKS Robin E3D board, but when I add the file Robin_e3.bin in my SD, the screen does not execute the update.

**Comment by makerbase-mks** [comment]
Hi! 
1. What screen are you using?
2. Robin E3 / E3D already have firmware. If you have not modified the firmware, you can use it directly on the Ender3 machine without upgrading
3. Robin E3 / E3D supports LCD12864 to display the firmware update progress

**Comment by JordiKoki** [comment]
I use a TFT35 V1.0 (with Firmware 1.0.5) in my CR10s, but doesn't works anything (hotend, bed, moves, fans...)

**Comment by makerbase-mks** [comment]
Hi! You can refer to it and link is : https://github.com/makerbase-mks/MKS-Robin-E3-E3D/wiki/Upgrade-with-MKS-TFT-Series

**Comment by spooky79** [comment]
I have the same problem, it comes to 100% and nothing is happening, I'm using visual studio code, any solution?

**Comment by aspaixao** [comment]
I have the same with my e3d and I using a CoreXY and configuration to ender 6

**Comment by sergiofagundes** [comment]
FIXED 100% working:

 the board if using a 4GB sdcard,
I tried with 8GB/16GB/32GB and none of them worked.
So I tried a 4GB sdcard and it worked.

I used the Sdcard on the LCD sdcard slot, but I think it should work also in the mks robin board sdcard slot also with only 4GB sdcard.
