### ISSUE TITLE
Can't change colors with gcode with neopixel firmware 

### ISSUE THREAD

**Issue by jechs83** [makerbase-mks/MKS-Robin-E3-E3D#23]
I can't control colors with gcode , and it start led strip white color and stay that color

The last upload firmware neopixel 
 HD-V1_003 Marlin2.0.1_20200515

**Comment by makerbase-mks** [comment]
Can you refer to Robin E3-E3D Wiki? I has a tutorial about how to use neopixel light strip.

**Comment by makerbase-mks** [comment]
Can you provide and you buy light strip link? I need check it use drive and power and so on? Because board's interface use 5V power and light strip has WS2812B or other adafruit Neopixel LED driver.
