### ISSUE TITLE
compatible now with platformIO adding -> ststm32@5.4.3

### ISSUE THREAD

**Issue by soyatlas** [makerbase-mks/MKS-Robin-E3-E3D#24]
please take note comment the original and add with the following line 
[env:mks_robin_e3]
#platform      = ststm32 
platform      = ststm32@5.4.3

[env:mks_robin_e3d]
#platform      = ststm32
platform      = ststm32@5.4.3

This information came to me from the 3DWork.io portal and its administrator Juanjo R.

**Comment by anilcancakir** [comment]
Default Marlin 2.0 are using `platform = ststm32@<6.2.0`.

**Comment by makerbase-mks** [comment]
Hi! I has add it @<6.2.0
