### ISSUE TITLE
Conexion mks robin e3d y sensor inductivo

### ISSUE THREAD

**Issue by tolapoto** [makerbase-mks/MKS-Robin-E3-E3D#26]
Donde se debe de conectar correctamente el sensor inductivo en la plana robin e3d para no perder el final de carrera del eje z?

**Comment by makerbase-mks** [comment]
Sorry, can you describe it more clearly?

**Comment by hanger13** [comment]
Como conectar Sensor SN04 e como configurar no Marlin.

**Comment by makerbase-mks** [comment]
1、SN04, you need use NPN type
![image](https://user-images.githubusercontent.com/12979070/93035922-f119ee80-f670-11ea-9938-0083a67585bf.png)

**Comment by tolapoto** [comment]
Gracias, lo he conseguido. Gracias a todos

**Comment by Emeale2021** [comment]
Ola, estou tentando instalar o senr indutivo na MKS Robin e3d, gostaria de saber qual pino conectar conectar

**Comment by Emeale2021** [comment]
Hello, I am trying to install the inductive senr on the MKS Robin e3d, I would like to know which pin to connect to
