### ISSUE TITLE
Robin_E3D-doesn't_update

### ISSUE THREAD

**Issue by TxasMan3D** [makerbase-mks/MKS-Robin-E3-E3D#27]
Robin_E3D+tft35 v1.0
Using VSCode to generate an updated Robin_e3.bin file. 
I save it in the MicroSD card and put it in the TF slot of the motherboard. 
When I repower the printer, board doesn't update with new file
Looks like the eeprom is disabled but, how can i enable it without comunication with the board?

**Comment by makerbase-mks** [comment]
You can try to change TF card or format it. Can you provide your motherboard updating picture?

**Comment by TxasMan3D** [comment]
I have used two different TF cards and my pc has no problems to read them. Yes, of course. I will send you by email the whole folder with the updated firmware.

**Comment by TxasMan3D** [comment]
Due to the size of the folder i can’t send it so i send you the updated “firmware.bin” file that is located in .pio/build/mks_robin_e3. The name of the file was changed to “Robin_e3.bin”.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: makerbase<mailto:notifications@github.com>
Enviado: miércoles, 5 de agosto de 2020 3:17
Para: makerbase-mks/MKS-Robin-E3-E3D<mailto:MKS-Robin-E3-E3D@noreply.github.com>
CC: TxasMan3D<mailto:adicto_al_snow@hotmail.com>; Author<mailto:author@noreply.github.com>
Asunto: Re: [makerbase-mks/MKS-Robin-E3-E3D] Robin_E3D-doesn't_update (#27)


You can try to change TF card or format it. Can you provide your motherboard updating picture?

**Comment by makerbase-mks** [comment]
No! You need copy Robin_e3.bin file to tf card, doesn't firmware.bin rename Robin_e3.bin 
You can download MKS Robin E3-E3D path Robin_e3.bin file update

**Comment by TxasMan3D** [comment]
I had downloaded that one also but i have a bmg extruder fitted and i changed the steps in the firmware to get them saved in the motherboard, otherwise my problem has been fixed. I thought that the file that need to be copied was firmware.bin. I have try with the Robin_e3 one and looks like it has been read. Thank you!
