### ISSUE TITLE
Bin files and config.h

### ISSUE THREAD

**Issue by RJD2two** [makerbase-mks/MKS-Robin-E3-E3D#29]
I appreciate the .bin files for me to just load and update my MKS Robin E3D. Can you release the config.h files along with it please.

For example you just released 2.0.6 with TMC2209 .bin file. I would like to try add bl touch to that config file

**Comment by makerbase-mks** [comment]
Hi! You can refer to https://github.com/makerbase-mks/MKS-Robin-E3-E3D/tree/master/firmware/marlin2.0%20for%20Ender3/Marlin Configuration.h and Configuration_adv.h file. 
The Robin_e3_TMC2209.bin build by this config.
