### ISSUE TITLE
bigthreetech tft24 não funciona na MKs Robin e3d. help

### ISSUE THREAD

**Issue by hanger13** [makerbase-mks/MKS-Robin-E3-E3D#30]
Tenho uma mks Robin e3d comprei um bigthreetech tft24 v1.2 . Porém não consigo por pra funcionar pela porta auxiliar 1 (aux1) apresentando o erro printer nota atached. Já mudei o baud rat para todos os valores e nada. Alguém na mesma situação?

**Comment by makerbase-mks** [comment]
Hi! You need to do the following：
1、Connect TFT to Robin E3D, Must be correct
2、#define SERIAL_PORT -1 and #define SERIAL_PORT_2 1 ， #define BAUDRATE 250000
3、TFT baud rate must same as motherboard

**Comment by hanger13** [comment]
tentei de tudo, nem via usb conecta.

**Comment by makerbase-mks** [comment]
Usually only these three settings are needed to work normally. I think you need to confirm the TFT to AUX-1 wiring.

**Comment by hanger13** [comment]
Confirmado. Os pinos do RX tx sao normalmente invertidos na mks Robin. Será que a placa está com problemas? Em curto Os pinos RX tx ?

**Comment by makerbase-mks** [comment]
![image](https://user-images.githubusercontent.com/12979070/91514057-64ed9480-e918-11ea-9863-74c51a7339fd.png)

**Comment by hanger13** [comment]
Essa é boa exata conexão que estou usando.mesmo assim não conecta de jeito nenhum. "Nenhuma impressora encontrar." Não movimenta nenhum eixo não habilita nenhuma saída de fan, hot end , mesa... Enfim não funciona.

**Comment by makerbase-mks** [comment]
Can you provide your configuration.h file to me?

**Comment by hanger13** [comment]
pinos rx tx em curto.vou adquirir outra placa

**Comment by makerbase-mks** [comment]
You TFT？

**Comment by hanger13** [comment]
Sim Meu TFT.Em 5 de set de 2020 08:31, makerbase <notifications@github.com> escreveu:

You TFT？

**Comment by makerbase-mks** [comment]
I will colse this problem.
