### ISSUE TITLE
TMC Connection error

### ISSUE THREAD

**Issue by moritzraphael** [makerbase-mks/MKS-Robin-E3-E3D#32]
I have the TMC 2225 Drivers and I get every time a TMC connection error.

**Comment by makerbase-mks** [comment]
1. Configuration.h file: Setting driver type is TMC2208, becase TMC2225 is same as TMC2208;
2. You need setting motherboard as use uart mode
3. You need use DC12/24V power input

**Comment by moritzraphael** [comment]
How can I get the Configuration.h file on to the board?

**Comment by makerbase-mks** [comment]
You can download MKS Robin E3-E3D path Robin_e3.bin file and copy it to tf card update it, and use DC12/24V power input. This firmware can be used normally.

**Comment by makerbase-mks** [comment]
@moritzraphael 
It‘s solved?

**Comment by moritzraphael** [comment]
Yes, thank you for helping.
