### ISSUE TITLE
Bootloader that doesn't beep and display 'boot' when turned on?

### ISSUE THREAD

**Issue by gohan01** [makerbase-mks/MKS-Robin-E3-E3D#35]
Hi

Is it possible to get a version of the bootloader that does not beep and does not display "boot" when turned on?

Thanks!

**Comment by makerbase-mks** [comment]
You can refer to it
![image](https://user-images.githubusercontent.com/12979070/93043325-02b8c180-f684-11ea-9ba1-91d97b3910a4.png)

**Comment by gohan01** [comment]
Thank you!

**Comment by taveirapablo** [comment]
How to install this?
