### ISSUE TITLE
Activating Bltouch Support rom problem

### ISSUE THREAD

**Issue by azzell** [makerbase-mks/MKS-Robin-E3-E3D#37]
Hi
When I try activating bltouch support and babystepping on your version of marlin i get an error of not enough rom memory:
c:/users/user/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/bin/ld.exe: .pio\build\mks_robin_e3\firmware.elf section `.rodata' will not fit in region `rom'
c:/users/user/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/bin/ld.exe: region `rom' 
overflowed by 1140 bytes256kb
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\mks_robin_e3\firmware.elf] Error 1

Way around it was to disable  M503 but u would like to save this function is this board really has only 256 kb of rom storage?

**Comment by makerbase-mks** [comment]
MKS Robin E3, E3D CUP is STM32F103RCT6, so ROM/RAM is 256KB/48KB
