### ISSUE TITLE
Fan is always on...

### ISSUE THREAD

**Issue by piberry** [makerbase-mks/MKS-Robin-E3-E3D#40]
Hi!
I installed the board a few days ago. Unfortunately the fan is not controllable (always on) which is not a firmware problem. What part do i need to replace? If the fan was dead, i would replace Q3...
I can solder pretty well but i´m not an electronic engineer. I would be glad if someone could help me out.

Thanks!

**Comment by makerbase-mks** [comment]
About Q3, i suggest you use AO3400
