### ISSUE TITLE
impossible to update firmware

### ISSUE THREAD

**Issue by Valoliin** [makerbase-mks/MKS-Robin-E3-E3D#41]
hello I'm trying to update my firmware but this is impossible the file on the sd card is not renamed.

I use the marlin firmware which is in the github

on the sd card at the root I put the file robin_e3.bin

I tested with a 1GB sd card and an 8GB one and another 16GB

I tried to format the sd card to FAT32, FAT16, EXFAT, NTFS

**Comment by mks-viva** [comment]
The name should be Robin_e3.bin, you need to pay attention to case.

**Comment by Valoliin** [comment]
use 1GB sd card  format fat16
