### ISSUE TITLE
mks robin e3d can not flash and no boot

### ISSUE THREAD

**Issue by RutaHunter** [makerbase-mks/MKS-Robin-E3-E3D#43]
Hi. I bought the mks robin e3d board. Downloaded the firmware https://github.com/makerbase-mks/MKS-Robin-E3-E3D/blob/ender3-3d-touch/firmware/marlin2.0.x%20bin/Robin_e3_TMC2209.bin, renamed Robin_e3.bin, copy to micro sd and inserted it into the board, turned on the power and no reaction. The blue diode is on and that's it, and there are 2 stripes on the screen. Without a flash drive, the board behaves the same way and does not boot. The bootloader may have broken? How to fix?

**Comment by mks-viva** [comment]
Can you provide picture about no boot ?

**Comment by RutaHunter** [comment]
[Looks]
![viber_2020-10-30_16-17-58](https://user-images.githubusercontent.com/66780747/97709659-c0303480-1acb-11eb-9e4d-b3029dc9eec9.jpg)
like this all the time. No movement

**Comment by mks-viva** [comment]
Hi! The 'boot' will be display only when you use LCD12864 or MKS LCD12864B, so, if you use LCD2004 and it's no display, because bootloader have not LCD2004 display.

**Comment by RutaHunter** [comment]
I know lcd2004 doesn't fit. My 12864b broke and until a new one came, I connected lcd2004. I think that in lcd2004 there should also be some movements when executing code in the processor. I know that when the code runs, the red led near the fan connector blink. And in case of successful firmware, the file on the flash card changes the extension to *.cur, but this also does not happen. I have flashed the processor via usart1.

**Comment by mks-viva** [comment]
@RutaHunter 
![image](https://user-images.githubusercontent.com/16629551/97823888-51362400-1cf5-11eb-9ca8-0b92cfc4c864.png)

**Comment by RutaHunter** [comment]
Flashing the bootloader didn't help either. Maybe I'm stitching it wrong somehow? Can there be any instructions for the firmware if the firmware does not work with the micro sd?

**Comment by mks-viva** [comment]
Can you provide your download bootloader procedure？I will check it.

**Comment by RutaHunter** [comment]
Pin boot0 (60) to 3.3v, connect UART to USART1, run STM Flash Loader Demonstrator
![1](https://user-images.githubusercontent.com/66780747/97981644-abadae00-1de3-11eb-8a22-57811d278a92.jpg)
![2](https://user-images.githubusercontent.com/66780747/97981663-b10af880-1de3-11eb-9ae1-f5fdd53ed2dd.jpg)
![3](https://user-images.githubusercontent.com/66780747/97981672-b36d5280-1de3-11eb-8327-f0b2577dff15.jpg)
![4](https://user-images.githubusercontent.com/66780747/97981675-b5cfac80-1de3-11eb-934d-2502b8f0556b.jpg)
Connect pin boot0 (60) to GND and restart device, but nothing

**Comment by mks-viva** [comment]
It seems everything is normal during the burning process

**Comment by RutaHunter** [comment]
Any ideas?

**Comment by mks-viva** [comment]
I need test it and i will use this flash process and check it work.

**Comment by mks-viva** [comment]
I test it and it's work and i use this flash process. So, i think your board 3.3V short to GND, because Boot0 has connect to gnd diretly, you need disconnect it

**Comment by RutaHunter** [comment]
Again flash bootloader, disconnect boot 0 from board, insert micro sd with firmware and turned on power, but same

**Comment by sl1pkn07** [comment]
> connect UART to USART1

how?

greetings

**Comment by mks-viva** [comment]
You need use STM32 PA9-TX1,PA10-RX1(AUX-1 interface)

**Comment by RutaHunter** [comment]
> You need use STM32 PA9-TX1,PA10-RX1(AUX-1 interface)
> 
> 1. Disconnect boot0
> 2. USB serial module's TX connect to AUX-1 RX，USB serial module's RX connect to AUX-1 TX，GND connect to GND，5V connect to 5V
> 3. Boot0 connect to 3.3V
> 4. Run STMFlashLoader Demo and add file
> 5. Download
> 
> I has use this flash process and it is work.

I did exactly that, but the program in the processor does not start.


> you mean connect PB6 and PB7 to USB UART dongle?
> 
> https://community.st.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&versionId=0680X000006qOsl&operationContext=CHATTER&contentId=05T0X00000NPN0r
> 
> is not posible use the SWD port for use with STLink?

![aux1](https://user-images.githubusercontent.com/66780747/98330517-a7fc7000-200b-11eb-8376-ed592d1ff716.png)

**Comment by mks-viva** [comment]
Needn't use STLink, just use a simple USB to serial port module, like this:
[Robin e3 use STMFlashLoader Demo.zip](https://github.com/makerbase-mks/MKS-Robin-E3-E3D/files/5499499/Robin.e3.use.STMFlashLoader.Demo.zip)
![image](https://user-images.githubusercontent.com/16629551/98333256-46ec9080-203b-11eb-8237-fd6fe88f02a1.png)
![image](https://user-images.githubusercontent.com/16629551/98333229-39370b00-203b-11eb-8d85-bd71f7c3ff2c.png)

**Comment by RutaHunter** [comment]
I wrote that the processor reads and writes well. It doesn't run the program.

**Comment by mks-viva** [comment]
> I wrote that the processor reads and writes well. It doesn't run the program.

When you use boot0 to connect to 3.3V, be sure to disconnect boot0 and GND. If you don’t do this, I have to suspect that the chip is damaged, because your subsequent steps don’t seem to have any problems.

**Comment by RutaHunter** [comment]
Hi. I take my 12864lcd/ If i flash to processor this bootloader https://github.com/makerbase-mks/MKS-Robin-E3-E3D/blob/ender3-3d-touch/firmware/Bootloader/MKS%20Robin%20E3_E3D%20TEST.hex then the screen says "boot" and the speaker beeps.
![IMG_20201114_120005](https://user-images.githubusercontent.com/66780747/99145044-4fb51600-267c-11eb-9561-881203d7dd5d.jpg)

if I flash something else, then only the backlight is on on the screen and nothing happens
![IMG_20201114_132105](https://user-images.githubusercontent.com/66780747/99145071-7c692d80-267c-11eb-9499-ede7ab4c211d.jpg)

**Comment by mks-viva** [comment]
You can flash MKS Robin E3_E3D TEST.hex and this hex file include bootloader, and after, you can update Robin_e3.bin file.

**Comment by RutaHunter** [comment]
> 
> 
> You can flash MKS Robin E3_E3D TEST.hex and this hex file include bootloader, and after, you can update Robin_e3.bin file.

It did not help

**Comment by mks-viva** [comment]
![image](https://user-images.githubusercontent.com/16629551/99923511-ff6f3f80-2d70-11eb-85f1-21fb0c569606.png)
If this can be started normally, I think it's working ok.

**Comment by mks-viva** [comment]
I will close this question temporarily.

**Comment by ostapoff** [comment]
I have the same issue with my MKS Robin e3d and MKS LCD12864B.

This is how it boots up: https://youtu.be/nOsbkkQBBko

This is how it handles the firmware update: https://youtu.be/mu0gxG2ySPE

Sometimes it is possible to make it start working by inserting an xd card but it works very rarely. And if it works the contrast is too low though it is set to 205. When I get into the corresponding menu the contrast of the screen gets magically repaired: https://youtu.be/z7TEHHgfpps

Also when I attach a screen from the Ender-3 it works like a charm via ext1+ext2 as well as via ext3: https://youtu.be/eUXtF-SC6lw

Of course for the Ender's screen I use **#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER**  and for the MKS LCD12864B the **#define MKS_LCD12864**
