### ISSUE TITLE
Firmware for ender 5?

### ISSUE THREAD

**Issue by arsene-r2** [makerbase-mks/MKS-Robin-E3-E3D#49]
On the youtube channel, the board is advertised for the Ender 5 as well but theres no firmware for the Ender 5 on here. Can you make a firmware for the Ender 5 please?

**Comment by mks-viva** [comment]
Thank you for your feedback, we will deal with it, you can also refer to the link: https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality
