### ISSUE TITLE
TMC Connection Error

### ISSUE THREAD

**Issue by ricardonato** [makerbase-mks/MKS-Robin-E3-E3D#55]
I have connected the TMC2209 v1.0 drivers to my new MKS Robin E3D (003) board without modifying anything.

I have updated the "firmware bin for Ender3 (TMC2209)"
https://github.com/makerbase-mks/MKS-Robin-E3-E3D/tree/ender3-3d-touch/firmware/firmware%20bin%20for%20Ender3(TMC2209)

When Marlin finishes booting, the message appears:
"TMC Connection Error"

**Comment by mks-viva** [comment]
Hi! You need to do the following so that TMC will not report errors
1. Usrt mode set in E3D motherboard（Use jumpers connect it）
![image](https://user-images.githubusercontent.com/16629551/102426935-4c31f780-404b-11eb-8a14-9618936d407b.png)
2. You need use DC12-24V power

**Comment by ricardonato** [comment]
Thank you. Problem solved
