### ISSUE TITLE
 compilation of firmeware for MKS-Robin-E3-E3D

### ISSUE THREAD

**Issue by diegomsdos** [makerbase-mks/MKS-Robin-E3-E3D#57]
Good morning, what option do I use in the AIO - project tasks platform to compile the firmeware for
MKS-Robin-E3-E3D

**Comment by mks-viva** [comment]
Sorry, I personally don’t know AIO-project tasks platform, but you can use Vscode.

**Comment by mks-viva** [comment]
Hi! I will close this issues temporarily.
