### ISSUE TITLE
Question : Can the board be configured for 12V fans ?

### ISSUE THREAD

**Issue by imakiro** [makerbase-mks/MKS-Robin-E3-E3D#6]
Hello,
I would like to reduce the noise of the hotend fan, can the Robin-E3D V1.0 board be configured to use a 12V fan without a buck converter / step down voltage regulator ?
If so, how and which parameters to change in Marlin source code?

**Comment by makerbase-mks** [comment]
Hi! The safest way is that you can directly use a 12VDC module.
