### ISSUE TITLE
How to upload bootloader ?

### ISSUE THREAD

**Issue by Seelenkind** [makerbase-mks/MKS-Robin-E3-E3D#62]
Hi, 
how to upload bootloader ? 
i want to slience the beep at start

https://github.com/makerbase-mks/MKS-Robin-E3-E3D/tree/ender3-3d-touch/firmware/Bootloader

i connected PC with MKS Board with FTD232 USB to Serial Modul. 
but Flash Loader Demonstrator can not find Board , but connected as Com Port 8

thx

**Comment by mks-viva** [comment]
Hi! https://github.com/makerbase-mks/MKS-Robin-E3-E3D/issues/43

**Comment by Seelenkind** [comment]
> Hi! #43
Hi,
I already found this question in the archive and am not sure which of these pins should be pin 60?
Pin 60 should either be on 3.3. set or the connection to GND disconnected. But which one is it exactly?
Why isn't a jumper installed on the board to put the board in bootloader upload mode?
![image](https://user-images.githubusercontent.com/75549196/103480630-a36af280-4dd5-11eb-981f-7dd79421c763.png)

**Comment by mks-viva** [comment]
Hi! About 60pin map
![image](https://user-images.githubusercontent.com/16629551/103524196-16e53080-4eb8-11eb-9039-6810a2fb3a88.png)
This may be something we did not consider, I am sorry. But MKS Robin E3/E3D has TF update firmware function

**Comment by mks-viva** [comment]
Hi! If there is no response, then I will temporarily close this question.
