### ISSUE TITLE
Issue with Z-axis after Auto homing

### ISSUE THREAD

**Issue by Benji198599** [makerbase-mks/MKS-Robin-E3-E3D#65]
Hello, 

There is one issue with Z-axis after upload the firmware: 
- Firmware bin for Ender3 (TMC2209)
or
- marlin2.0 for Ender 3
or 
any another firmware which includes BLtouch

The Z- axis doesn't move manually (LCD - Motion - Move) after auto homing!
But it moves in the printer programm.... and again after the print programm.... 

could you please help?

**Comment by mks-viva** [comment]
Hi! Can you provide your motherboard's wiring ? You can try to bltouch‘s output signel connect to E3/E3D board's probe/e-stop interface.

**Comment by Benji198599** [comment]
problem solved!
