### ISSUE TITLE
Home and move issues

### ISSUE THREAD

**Issue by edvard5** [makerbase-mks/MKS-Robin-E3-E3D#66]
After Homing axis, move doesn't work, 3D touch is not leveling. End stops working fine, tested.
https://youtu.be/HgGHZkHkZOE

**Comment by mks-viva** [comment]
Hi! This looks like the program has stopped running after returning to home. You can try to use USB to connect to the motherboard, and the host computer can check the printed information after returning to home, and you can locate what caused the axis to be unable to move.

**Comment by edvard5** [comment]
I'll give it a try and report back

**Comment by mks-viva** [comment]
Ok!

**Comment by edvard5** [comment]
[ERROR] Error:!! STOP called because of BLTouch error - restart with M999
Error:Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)
two errors

**Comment by mks-viva** [comment]
Ok! Please tell me which firmware are you using?

**Comment by edvard5** [comment]
https://github.com/makerbase-mks/MKS-Robin-E3-E3D/blob/master/firmware/V1.1/Firmware%20bin%20for%20ender3/Marlin-2.0.6.1_for_ender3_TMC2209%2B3dtouch%2BZ_SAFE_HOMING.bin
this one with TFT35 1.0.7v

**Comment by mks-viva** [comment]
3D Touch's output signel need connect to probe/E-stop interface
![image](https://user-images.githubusercontent.com/16629551/104907630-5899cf00-59c0-11eb-8df3-c95e053e6110.png)

**Comment by edvard5** [comment]
![IMG_20210118_130905](https://user-images.githubusercontent.com/6080572/104907887-69315180-598e-11eb-8039-c24e0d2e8867.jpg)
Already connected, followed step by step tutorial

**Comment by edvard5** [comment]
Probelm still persists. need help 🌵

**Comment by mks-viva** [comment]
I am sorry! I seem to be doing the wrong guide.
![image](https://user-images.githubusercontent.com/16629551/104910676-a0225a00-59c4-11eb-8c4e-5266657c9231.png)

**Comment by mks-viva** [comment]
You need remove ender3 original Zstop

**Comment by edvard5** [comment]
offset set corectlly but it keeps pushing nozzle to bed with force until starts to skip

**Comment by edvard5** [comment]
after homing still same problem, can't manually move axis... like in the video

**Comment by edvard5** [comment]
managed to fix this with these steps
M502
M500
M999
then setting xyz offsets all over again.

**Comment by mks-viva** [comment]
I didn't think about it,
