### ISSUE TITLE
Urgent help required! ender 3 V2 LCD screen not supported

### ISSUE THREAD

**Issue by Salkio** [makerbase-mks/MKS-Robin-E3-E3D#68]
I need help. I compiled firmware and when I tried to flash nothing happened. I realized the screen was also off and beeping.
I thought maybe I had to enable the DWIN_CREALITY_LCD (Ender 3 V2 stock screen) however that did not compile and gave me this error code below. Please tell me I can fix this!

ERROR CODE: 

In file included from Marlin\src\lcd\dwin\dwin.h:29:0,
                 from Marlin\src\lcd\dwin\dwin.cpp:31:
Marlin\src\lcd\dwin\rotary_encoder.h:44:0: warning: "ENCODER_PULSES_PER_STEP" redefined
 #define ENCODER_PULSES_PER_STEP  4

In file included from Marlin\src\lcd\dwin\../../inc/MarlinConfigPre.h:47:0,
                 from Marlin\src\lcd\dwin\dwin.cpp:27:
Marlin\src\lcd\dwin\../../inc/Conditionals_LCD.h:377:0: note: this is the location of the previous definition
   #define ENCODER_PULSES_PER_STEP STD_ENCODER_PULSES_PER_STEP

Compiling .pio\build\mks_robin_e3\src\src\libs\W25Qxx.cpp.o
In file included from Marlin\src\lcd\dwin\rotary_encoder.cpp:37:0:
Marlin\src\lcd\dwin\rotary_encoder.h:44:0: warning: "ENCODER_PULSES_PER_STEP" redefined
 #define ENCODER_PULSES_PER_STEP  4

In file included from Marlin\src\lcd\dwin\../../inc/MarlinConfigPre.h:47:0,
                 from Marlin\src\lcd\dwin\rotary_encoder.cpp:33:
Marlin\src\lcd\dwin\../../inc/Conditionals_LCD.h:377:0: note: this is the location of the previous definition
   #define ENCODER_PULSES_PER_STEP STD_ENCODER_PULSES_PER_STEP

Compiling .pio\build\mks_robin_e3\src\src\libs\buzzer.cpp.o
Compiling .pio\build\mks_robin_e3\src\src\libs\crc16.cpp.o
In file included from Marlin\src\lcd\dwin\../../inc/../HAL/./STM32F1/HAL.h:36:0,
                 from Marlin\src\lcd\dwin\../../inc/../HAL/HAL.h:26,
                 from Marlin\src\lcd\dwin\../../inc/MarlinConfig.h:30,
                 from Marlin\src\lcd\dwin\rotary_encoder.h:34,
                 from Marlin\src\lcd\dwin\rotary_encoder.cpp:37:
Marlin\src\lcd\dwin\rotary_encoder.cpp: In function 'void Encoder_tick()':
Marlin\src\lcd\dwin\rotary_encoder.cpp:52:9: error: 'BEEPER_PIN' was not declared in this scope
   WRITE(BEEPER_PIN, 1);
         ^
Marlin\src\lcd\dwin\../../inc/../HAL/./STM32F1/fastio.h:33:42: note: in definition of macro 'WRITE'
 #define WRITE(IO,V)             (PIN_MAP[IO].gpio_device->regs->BSRR = (1U << PIN_MAP[IO].gpio_bit) << ((V) ? 0 : 16))
                                          ^~
Marlin\src\lcd\dwin\rotary_encoder.cpp:52:9: note: suggested alternative: 'TEMP_7_PIN'
   WRITE(BEEPER_PIN, 1);
         ^
Marlin\src\lcd\dwin\../../inc/../HAL/./STM32F1/fastio.h:33:42: note: in definition of macro 'WRITE'
 #define WRITE(IO,V)             (PIN_MAP[IO].gpio_device->regs->BSRR = (1U << PIN_MAP[IO].gpio_bit) << ((V) ? 0 : 16))
                                          ^~
Marlin\src\lcd\dwin\rotary_encoder.cpp: In function 'ENCODER_DiffState Encoder_ReceiveAnalyze()':
Marlin\src\lcd\dwin\rotary_encoder.h:46:34: error: 'BTN_EN1' was not declared in this scope
 #define BUTTON_PRESSED(BN) !READ(BTN_## BN)
                                  ^
Marlin\src\lcd\dwin\../../inc/../HAL/./STM32F1/fastio.h:32:42: note: in definition of macro 'READ'
 #define READ(IO)                (PIN_MAP[IO].gpio_device->regs->IDR & (1U << PIN_MAP[IO].gpio_bit) ? HIGH : LOW)
                                          ^~
Marlin\src\lcd\dwin\rotary_encoder.cpp:82:7: note: in expansion of macro 'BUTTON_PRESSED'
   if (BUTTON_PRESSED(EN1)) newbutton |= 0x01;
       ^~~~~~~~~~~~~~
Marlin\src\lcd\dwin\rotary_encoder.h:46:34: error: 'BTN_EN2' was not declared in this scope
 #define BUTTON_PRESSED(BN) !READ(BTN_## BN)
                                  ^
Marlin\src\lcd\dwin\../../inc/../HAL/./STM32F1/fastio.h:32:42: note: in definition of macro 'READ'
 #define READ(IO)                (PIN_MAP[IO].gpio_device->regs->IDR & (1U << PIN_MAP[IO].gpio_bit) ? HIGH : LOW)
                                          ^~
Marlin\src\lcd\dwin\rotary_encoder.cpp:83:7: note: in expansion of macro 'BUTTON_PRESSED'
   if (BUTTON_PRESSED(EN2)) newbutton |= 0x02;
       ^~~~~~~~~~~~~~
Marlin\src\lcd\dwin\rotary_encoder.h:46:34: error: 'BTN_ENC' was not declared in this scope
 #define BUTTON_PRESSED(BN) !READ(BTN_## BN)
                                  ^
Marlin\src\lcd\dwin\../../inc/../HAL/./STM32F1/fastio.h:32:42: note: in definition of macro 'READ'
 #define READ(IO)                (PIN_MAP[IO].gpio_device->regs->IDR & (1U << PIN_MAP[IO].gpio_bit) ? HIGH : LOW)
                                          ^~
Marlin\src\lcd\dwin\rotary_encoder.cpp:84:7: note: in expansion of macro 'BUTTON_PRESSED'
   if (BUTTON_PRESSED(ENC)) {
       ^~~~~~~~~~~~~~
Marlin\src\lcd\dwin\rotary_encoder.cpp:138:39: error: 'ENCODER_5X_STEPS_PER_SEC' was not declared in this scope
           else if (encoderStepRate >= ENCODER_5X_STEPS_PER_SEC) encoderMultiplier = 5;
                                       ^~~~~~~~~~~~~~~~~~~~~~~~
Marlin\src\lcd\dwin\rotary_encoder.cpp:138:39: note: suggested alternative: 'ENCODER_10X_STEPS_PER_SEC'
           else if (encoderStepRate >= ENCODER_5X_STEPS_PER_SEC) encoderMultiplier = 5;
                                       ^~~~~~~~~~~~~~~~~~~~~~~~
                                       ENCODER_10X_STEPS_PER_SEC
Marlin\src\lcd\dwin\dwin.cpp:174:51: error: 'DEFAULT_XJERK' was not declared in this scope
 constexpr float default_max_jerk[]            = { DEFAULT_XJERK, DEFAULT_YJERK, DEFAULT_ZJERK, DEFAULT_EJERK };
                                                   ^~~~~~~~~~~~~
Marlin\src\lcd\dwin\dwin.cpp:174:51: note: suggested alternative: 'DEFAULT_EJERK'
 constexpr float default_max_jerk[]            = { DEFAULT_XJERK, DEFAULT_YJERK, DEFAULT_ZJERK, DEFAULT_EJERK };
                                                   ^~~~~~~~~~~~~
                                                   DEFAULT_EJERK
Marlin\src\lcd\dwin\dwin.cpp:174:66: error: 'DEFAULT_YJERK' was not declared in this scope
 constexpr float default_max_jerk[]            = { DEFAULT_XJERK, DEFAULT_YJERK, DEFAULT_ZJERK, DEFAULT_EJERK };
                                                                  ^~~~~~~~~~~~~
Marlin\src\lcd\dwin\dwin.cpp:174:66: note: suggested alternative: 'DEFAULT_EJERK'
 constexpr float default_max_jerk[]            = { DEFAULT_XJERK, DEFAULT_YJERK, DEFAULT_ZJERK, DEFAULT_EJERK };
                                                                  ^~~~~~~~~~~~~
                                                                  DEFAULT_EJERK
Marlin\src\lcd\dwin\dwin.cpp:174:81: error: 'DEFAULT_ZJERK' was not declared in this scope
 constexpr float default_max_jerk[]            = { DEFAULT_XJERK, DEFAULT_YJERK, DEFAULT_ZJERK, DEFAULT_EJERK };
                                                                                 ^~~~~~~~~~~~~
Marlin\src\lcd\dwin\dwin.cpp:174:81: note: suggested alternative: 'DEFAULT_EJERK'
 constexpr float default_max_jerk[]            = { DEFAULT_XJERK, DEFAULT_YJERK, DEFAULT_ZJERK, DEFAULT_EJERK };
                                                                                 ^~~~~~~~~~~~~
                                                                                 DEFAULT_EJERK
*** [.pio\build\mks_robin_e3\src\src\lcd\dwin\rotary_encoder.cpp.o] Error 1
Marlin\src\lcd\dwin\dwin.cpp: In function 'void make_name_without_ext(char*, char*, int)':
Marlin\src\lcd\dwin\dwin.cpp:1541:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (len > maxlen) { // Keep the name short
       ~~~~^~~~~~~~
Marlin\src\lcd\dwin\dwin.cpp: In function 'void HMI_AudioFeedback(bool)':
Marlin\src\lcd\dwin\dwin.cpp:2140:5: error: 'buzzer' was not declared in this scope
     buzzer.tone(100, 659);
     ^~~~~~
Marlin\src\lcd\dwin\dwin.cpp:2140:5: note: suggested alternative: 'bzero'
     buzzer.tone(100, 659);
     ^~~~~~
     bzero
Marlin\src\lcd\dwin\dwin.cpp:2145:5: error: 'buzzer' was not declared in this scope
     buzzer.tone(40, 440);
     ^~~~~~
     buzzer.tone(40, 440);
     ^~~~~~
     bzero
compilation terminated due to -fmax-errors=5.
*** [.pio\build\mks_robin_e3\src\src\lcd\dwin\dwin.cpp.o] Error 1

**Comment by mks-viva** [comment]
Hi! MKS Robin E3/E3D can't support Dwen screen yet.
