### ISSUE TITLE
E3D "power supply" and "12-24V output" connectors

### ISSUE THREAD

**Issue by fantomsbg** [makerbase-mks/MKS-Robin-E3-E3D#69]
My original Ender 3 board is v4.2.2

![image](https://user-images.githubusercontent.com/73711113/106352924-7a178680-62ef-11eb-9221-d36e6bcb3a4a.png)
![image](https://user-images.githubusercontent.com/73711113/106352810-aaaaf080-62ee-11eb-9f8c-275985c505db.png)

Its power connector is located to the E3D "12-24V output" place. So I have to connect the power leads to it and the fan leads to "power supply" connector.
Is it safe and will the fuses fork correctly if the board is power supplied from the "12-24V output" connector?

**Comment by mks-viva** [comment]
Hi! 12/24 output interface depends on the power supply voltage you provide.

**Comment by fantomsbg** [comment]
My question was if I can connect the power supply leads to 12-24V output connector?

**Comment by mks-viva** [comment]
Yes, you can.

**Comment by fantomsbg** [comment]
Is there a fuse to protect this "12-24V output" when it become an input power supply connector?
If there are no fuses this can cause a serious problems?
According to me the fuse is only for the "power supply" connector.
