### ISSUE TITLE
hi just another question about SERIAL PORT 

### ISSUE THREAD

**Issue by ptitpuma** [makerbase-mks/MKS-Robin-E3-E3D#71]
hi just another question about that
hOw should i configurate this to add a tft 35 ?

_Originally posted by @ptitpuma in https://github.com/makerbase-mks/MKS-Robin-E3-E3D/issues/56#issuecomment-770359928_

**Comment by mks-viva** [comment]
Hi! You need set it in configuration.h file
1. #define SERIAL_PORT 1 (AUX-1 interface)
2. #define BAUDRATE 250000 (same as MKS TFT35)

**Comment by mks-viva** [comment]
If have not response，I will close this issues temprarily
