### ISSUE TITLE
MKS Robin E3 - Octoprint Serial 

### ISSUE THREAD

**Issue by Salkio** [makerbase-mks/MKS-Robin-E3-E3D#72]
I have been trying to connect this board to octoprint and for the life of me I cannot get it working. 
Can’t connect with /dev/ttyUSB0 or something. I have tried everything. Tried adding a * does not work.

**Comment by mks-viva** [comment]
Hi! You want to Klipper firmware?

**Comment by mks-viva** [comment]
You can send command ls /dev/serial/by-id/*  get serial
