### ISSUE TITLE
Robin E3 boot Ender 3 Pro

### ISSUE THREAD

**Issue by TheKillerOfMarsh** [makerbase-mks/MKS-Robin-E3-E3D#73]
Good evening, let's see if you can help me, I have compiled 2.0.6.1 for my Mks Robin E3 v.  1.0 correctly without errors, I just needed to change the extruder steps for my Ender 3 Pro and it updates correctly but it hangs on the Marlin logo, I have seen a .hex here is for that type of hang and where is the hex put?  Greetings.

**Comment by mks-viva** [comment]
Hi! I has check marlin config about ender 3 pro, Link:
https://github.com/MarlinFirmware/Configurations/blob/import-2.0.x/config/examples/Creality/Ender-3%20Pro/CrealityV1/Configuration.h
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 400, 93 }
![image](https://user-images.githubusercontent.com/16629551/106976470-68bcf700-6793-11eb-94a9-9bbeb36045f7.png)

**Comment by TheKillerOfMarsh** [comment]
Hi! My problem is not the configuration of the extruder steps, the problem is that after compiling the Marlin downloaded from here, it does the update well and it hangs on the Marlin logo, and I only modify the steps and do not touch anything else, in  change the .bin also downloaded from here is perfect.  I don't know what can change?

**Comment by mks-viva** [comment]
You mean hex file?

**Comment by TheKillerOfMarsh** [comment]
Yes, I mean that when updating well and restarting it remains frozen in the Marlin logo, if with that hex file it could be solved?  incidentally, how is the hex file used?  greetings and thanks!

**Comment by mks-viva** [comment]
This is not helpful, because the same marlin firmware settings, bin and hex are the same

**Comment by mks-viva** [comment]
So, I will close this issues
