### ISSUE TITLE
I need firmware ".bin" file for ENDER 5

### ISSUE THREAD

**Issue by azatalp** [makerbase-mks/MKS-Robin-E3-E3D#74]
I'try to do any kind of think for setup on card. But whatever I try cant setup on mks e3 card. Every time gave me error. How 2.0.6.1 is freeze on screen after %100. Please just give working 2.0.6 fw .bin file.

**Comment by azatalp** [comment]
Why anyone doesn't give me any kind of help??

**Comment by mks-viva** [comment]
Hi！I am sorry！We have not add bin file for ender5，we  will add it after february 24

**Comment by azatalp** [comment]
Ok I will wait for it

**Comment by arsene-r2** [comment]
Hello, any updates on this?

**Comment by azatalp** [comment]
I'm still waiting for this..

**Comment by azatalp** [comment]
> Hi！I am sorry！We have not add bin file for ender5，we will add it after february 24

24 feb is passed? Please help us.

**Comment by mks-viva** [comment]
I has upload it, you can test it, if have bug and i will fix it

**Comment by mks-viva** [comment]
https://github.com/makerbase-mks/MKS-Robin-E3-E3D/tree/master/firmware/V1.1

**Comment by mks-viva** [comment]
I will close this issues temporily
