### ISSUE TITLE
Firmware for CR10S5+BL touch

### ISSUE THREAD

**Issue by countcobolt** [makerbase-mks/MKS-Robin-E3-E3D#75]
Hi all

I am wondering if there is a configuration file for the CR10S5? I will receive the board soonish, but want to make sure I don't brick it. 
I did already compile a version already with platformio, but to enable TMC_Debug I had to disable SD Card support. Will this give issues if I make a mistake and want to install a new version (using an SD Card). 
Is there a tutorial to install firmware using the STLink app?

**Comment by mks-viva** [comment]
No, you only change some parameters and build it

**Comment by mks-viva** [comment]
I will close this issues temporarily
