### ISSUE TITLE
Build Error MKS Robin E3D

### ISSUE THREAD

**Issue by Therminius** [makerbase-mks/MKS-Robin-E3-E3D#76]
Hello 

I got mayor error during trying to compile - Firmware\V1\Ender3 TMC2209 - build from Your repository.

 I downloaded all files from Firmware. The problem only occurs with these files. Others can be processed normally - .bin is generated.

![Bez tytułu](https://user-images.githubusercontent.com/79075359/107913109-12ed0980-6f60-11eb-80b7-a71d6ac06068.png)

**Comment by mks-viva** [comment]
Hi! I has try to compile it, but has promble same as your compile and i think it was caused by the platformio update
