### ISSUE TITLE
SD not working and firmware update

### ISSUE THREAD

**Issue by vinacc** [makerbase-mks/MKS-Robin-E3-E3D#77]
I just got the Robin E3 card with firmware 2.0.6. Mounted on my Ender 3 I cannot update the firmware. Inserting the bin file inside the SD gives me the SD ERR message. How can I solve?

![IMG_6860](https://user-images.githubusercontent.com/304084/107951637-f15c4400-6f98-11eb-9afc-ecd52359db4f.jpeg)

**Comment by mks-viva** [comment]
Hi! You can try to format the TF card, and the format is FAT32

**Comment by vinacc** [comment]
Hi, yes I tried to reformat it in FAT32 format but it doesn't work. I have installed OctoPi and connected a Raspberry to my Ender 3. When I start OctoPi the SD inside the Robin E3 is seen and I can also read and write but when I disconnect the raspberry the SD is no longer seen.

**Comment by mks-viva** [comment]
Can you try to re-insert the card or replace the TF card to test. If this error occurs, the card status is not detected

**Comment by vinacc** [comment]
already tried, the board is enabled only after connecting the raspberry. And unfortunately I am unable to perform a software update

**Comment by mks-viva** [comment]
I suggest you use a new TF card

**Comment by vinacc** [comment]
Through a software such as Repetier Host, by connecting the card to my Mac and sending the M21 command to the printer, the SD is mounted and viewed correctly. The problem is that turning off the printer loses the setting. It is as if the SD on the firmware were disabled by default. Is it possible to update the firmware without using the SD?

**Comment by mks-viva** [comment]
Can you provide your firmware to me and i will test it?

**Comment by vinacc** [comment]
> Can you provide your firmware to me and i will test it?


[Robin_e3.bin.zip](https://github.com/makerbase-mks/MKS-Robin-E3-E3D/files/6134898/Robin_e3.bin.zip)

**Comment by mks-viva** [comment]
I'm sorry, I forgot to reply you, your firmware I updated without any problems, maybe you need to format the TF card, or replace the TF card.
