### ISSUE TITLE
Build Error since latest Visual Studio update

### ISSUE THREAD

**Issue by TxasMan3D** [makerbase-mks/MKS-Robin-E3-E3D#79]
Hello, i'm trying to build "Marling-bugfix-2.0.x" firmware with Visual Studio. This firmware was succesfully built an used during last year. The issue appears with the latest update of Visual Studio software. Maybe i have to modify or include something but i dont know what to do. Need help. 
Thank you!

![MKS-Linker_Script-Error](https://user-images.githubusercontent.com/69200523/108196308-42934180-7119-11eb-96b7-e2b786c09ff3.jpg)

**Comment by TxasMan3D** [comment]
Also have the same issue with the latest repository firmwares "Marlin-2.0.6.1_for_ender3_TMC2209...."

**Comment by mks-viva** [comment]
May be use the latest version marlin

**Comment by TxasMan3D** [comment]
Also have the same issue using the Marlin 2.0.7.2 configuration files...

**Comment by mks-viva** [comment]
I will test the latest version marlin

**Comment by mks-viva** [comment]
![image](https://user-images.githubusercontent.com/16629551/109098664-a989a980-775c-11eb-996d-4de0f734f271.png)
I test it is OK, My firmware
[Marlin-bugfix-2.0.x.zip](https://github.com/makerbase-mks/MKS-Robin-E3-E3D/files/6040334/Marlin-bugfix-2.0.x.zip)
