### ISSUE TITLE
V1.0 and V1.1

### ISSUE THREAD

**Issue by ll777** [makerbase-mks/MKS-Robin-E3-E3D#80]
What is the difference between the V1.0 and V1.1 Firmware? Their description is the same:
V1.0 - Upload E3/E3D V1.1 firmware
V1.1 - Upload E3/E3D V1.1 firmware

**Comment by mks-viva** [comment]
Hi, yon? can refer to hardware path information

**Comment by ll777** [comment]
The Full path for them is:
https://github.com/makerbase-mks/MKS-Robin-E3-E3D/tree/master/firmware
where I can find both folders 
https://github.com/makerbase-mks/MKS-Robin-E3-E3D/tree/master/firmware/V1.0
and
https://github.com/makerbase-mks/MKS-Robin-E3-E3D/tree/master/firmware/V1.1

**Comment by mks-viva** [comment]
Like this: 
![image](https://user-images.githubusercontent.com/16629551/108614083-87c5b500-7432-11eb-9553-6101371c00ea.png)

**Comment by Amppa** [comment]
@mks-viva 
So if the PCB print with "MKS Robin E3 V1.0", means it is V1.0 hardware right?
![image](https://user-images.githubusercontent.com/7997847/112714295-be508d00-8f14-11eb-8181-8f5a75887a90.png)

I noticed that V1.0 used Marlin ver2.0.6. The V1.1 is built from Marlin ver2.0.6.1
I wonder if I can build V1.0 on the newest Marlin

**Comment by mks-viva** [comment]
> @mks-viva
> So if the PCB print with "MKS Robin E3 V1.0", means it is V1.0 hardware right?
> ![image](https://user-images.githubusercontent.com/7997847/112714295-be508d00-8f14-11eb-8181-8f5a75887a90.png)
> 
> I noticed that V1.0 used Marlin ver2.0.6. The V1.1 is built from Marlin ver2.0.6.1
> I wonder if I can build V1.0 on the newest Marlin

Yes，you can. You only define motherboard is MKS_ROBIN_E3_V1_0
