### ISSUE TITLE
Bootloader

### ISSUE THREAD

**Issue by krzysziekz** [makerbase-mks/MKS-Robin-E3-E3D#84]
Hi.

I've E3D. How to update bootloader, the startup "beep" is very annoying. Is that safe process?

[booloaders](https://github.com/makerbase-mks/MKS-Robin-E3-E3D/tree/master/firmware/Bootloader)

**Comment by mks-viva** [comment]
Hi! You can use Jflash download it

**Comment by ll777** [comment]
the file can be copied to the sd card or it requires an additional hardware to flash it?

**Comment by mks-viva** [comment]
> the file can be copied to the sd card or it requires an additional hardware to flash it?

No

**Comment by mks-viva** [comment]
https://github.com/makerbase-mks/MKS-Robin-E3-E3D/issues/31

**Comment by ll777** [comment]
Oh OK, thanks I was reading this post  #43 and I  have a usb to serial adapter like this one https://pt.aliexpress.com/item/1005001877595087.html Would it work?

**Comment by mks-viva** [comment]
I recommend you to use JLINK

**Comment by shawe** [comment]
Can be flashed from an Arduino?
