### ISSUE TITLE
Firmware compiles but doesn't update the board

### ISSUE THREAD

**Issue by wiviolima** [makerbase-mks/MKS-Robin-E3-E3D#87]
On a E3 v1.0. able to flash the firmware, but the board always errors out when flashing - blue led blinks once or twice, then red led lights up and turns off. Firmware on sd card disappears, and I only find a .cur file. I`ve tried flashing other bins I've found and one of them flashes, but it isn't configured for my printer.

I've tried reinstalling everything on my PC, tried another computer, and still nothing.

I've tried the solutions on this  [link](https://github.com/MarlinFirmware/Marlin/issues/19363#issuecomment-691622797) and the one named Robin_e3.tassiolucas.zip' works, but the other one doesn't. While Robin_e3.tassiolucas.zip works, I need to tweak the code.

I have an ender 2 (150x150 build plate), with a RepRapDiscount FULL GRAPHIC Smart Controller (although I tried compiling without it and still no go).

**Comment by mks-viva** [comment]
Hi! You need copy Robin_e3.bin file to TF card and update.
