### ISSUE TITLE
Octoprint and MKS E3D V1.1 - Printer Hanged

### ISSUE THREAD

**Issue by pacocatech** [makerbase-mks/MKS-Robin-E3-E3D#89]
Hello folks,

I saw issues #18 and #19 that relate same problem but the problem continues.
I changed the baudrate to 115200 and increase buffersize after 10 mins printer hanged again.
MKS E3D v1.1 is compatible with Octoprint?
How to solve this HUGE problem?

**Comment by Sebe47** [comment]
cant even connect via Octoprint to the Printer :-(

**Comment by mks-viva** [comment]
Hi! I think, you can use pronterface via USB and printing gcode test, and i think it and it's work ok?
After, if you use Octoprint and it's not work, so, you need check Octoprint settings.

**Comment by mks-viva** [comment]
I will close this issues temprarily
