### ISSUE TITLE
how to use chinese simplified in ender3 default display and E3 motherboard

### ISSUE THREAD

**Issue by zyystudio** [makerbase-mks/MKS-Robin-E3-E3D#91]
I have gone through the site and successfully compiled the 2.0.6.1 marlin with E3 and 3d touch with my parameters to flash the ender3.
However I do see there is simplified chinese version for E3D. 
Is there documentation how to do that?
Thanks
Stanley

**Comment by zyystudio** [comment]
BTW the display model on ender3 by default is LCD12864

**Comment by zyystudio** [comment]
#define LCD_LANGUAGE zh_CN

**Comment by zyystudio** [comment]
?
It seems overflow the 256K of STM32F103RCT6 right?

**Comment by mks-viva** [comment]
Yes, if you use Chinese, it is easy to cause the Flash to be larger than 256kb. Therefore, you need to block the boot logo, etc. Maybe, you refer to **Marlin-2.0.6.1_E3D_V1.0_Chinese_TMC2209** source code and it's will make sense.

**Comment by zyystudio** [comment]
aha! it's you again! Thanks. That's a good idea! Lovely!

**Comment by zyystudio** [comment]
Wonderful! Solved! shrink several ones! Love you!

**Comment by mks-viva** [comment]
Haha! So, i will close this issues temporily.
