### ISSUE TITLE
3dtouchv2.0

### ISSUE THREAD

**Issue by zyystudio** [makerbase-mks/MKS-Robin-E3-E3D#94]
I tried the code with e3+2209+3dtouch and compiled successfully. The issue is that it forget the x and y spaces when starting to print. 
I also tried the compiled bin file from this repository with e3 2209 3dtouch. It happens the same one - once staring to print, it will stuck in the (0,0,0) and fastly move to the y value of the model.
Any idea? Can you try from your side?

**Comment by zyystudio** [comment]
https://user-images.githubusercontent.com/7643104/112749792-4909b880-8ff7-11eb-8ea4-8f098584ef58.MP4

see the video with both kind of firmware

**Comment by a4870010** [comment]
回零方向不对，因为2209驱动和原来是相反的，固件里修改一下方向就可以了

**Comment by zyystudio** [comment]
> 回零方向不对，因为2209驱动和原来是相反的，固件里修改一下方向就可以了

感觉你说的不对。一是这个刚刚开始打印，已经归零后的视频。二是偶尔后面有两次撞大运一样是可以正常打印出来的，但基本都是这个状态直接跑到（0，y，0）的位置开始打印。感觉是忘记了或者说是计算错误打印空间。 等官网回复吧

**Comment by a4870010** [comment]
如果切片没问题的话，电机正反也没问题的话，排除一下固件的问题，用marlin官方最新的bugfix固件刷写测试，一样一样排除。

**Comment by zyystudio** [comment]
Any update or test result from official side?
Thanks

**Comment by zyystudio** [comment]
sorry! I think I found the root cause. Thanks and please continue to make great product for Made In China!!!
