### ISSUE TITLE
error: #error "No E stepper plug left for Z2!

### ISSUE THREAD

**Issue by Niptoc** [makerbase-mks/MKS-Robin-E3-E3D#95]
Hello,

I want to compile MKS Robin E3 V1.0 for a CR-10 with a dual Z motor with marlin  2.0.7.2 and I get an error when compiliing:

``buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/../pins/pins.h:1410:8: error: #error "No E stepper plug left for Z2!``

I have set in `Configuration_adv.h` 
`#define NUM_Z_STEPPER_DRIVERS 2   // (1-4) Z options change based on how many`

In the pins definition I don't see PINs for Z2. ( `pins_MKS_ROBIN_E3_common.h`)
```
//
// Steppers
//
#define X_STEP_PIN                          PC0
#define X_DIR_PIN                           PB2
#define X_ENABLE_PIN                        PC13

#define Y_STEP_PIN                          PC2
#define Y_DIR_PIN                           PB9
#define Y_ENABLE_PIN                        PB12

#define Z_STEP_PIN                          PB7
#define Z_DIR_PIN                           PB6
#define Z_ENABLE_PIN                        PB8

#define E0_STEP_PIN                         PB4
#define E0_DIR_PIN                          PB3
#define E0_ENABLE_PIN                       PB5
```

**Comment by mks-viva** [comment]
Hi! MKS Robin E3 have not E1 axis, you can use Z2 interface

**Comment by Niptoc** [comment]
Hi, Sorry but I'm not sure to understand. 
What do you mean by using Z2 interface ?

**Comment by mks-viva** [comment]
![image](https://user-images.githubusercontent.com/16629551/113284683-8edabf80-931c-11eb-9001-d0ff6a1568b1.png)
Z1 and Z2 interface

**Comment by Niptoc** [comment]
This is what I plan to use. But are the Z1 and Z2 independant (Can we use them independantly) so that I can use the implemented feature to autocalibrate the Z axis.
When I check the drawing for PINs and the PIN configuration file there are no distinction for Z1 and Z2.

**Comment by mks-viva** [comment]
They are connected in parallel. Since MKS Robin E3 has only 4 axes, you cannot define independent Z2

**Comment by Niptoc** [comment]
Ok, thank you for the answer, it is clear now :)
