### ISSUE TITLE
Accidentally touched part cooling fan wires. Black smoke and now part cooling always on..

### ISSUE THREAD

**Issue by danbrianwhite** [makerbase-mks/MKS-Robin-E3-E3D#99]
Hello MKS team. I recently had an accident where I touched/shorted the part cooling fan wires together. There was black smoke from the board. Now the part cooling fan is always on (partially). Can I fix this and how? Or is there a workaround you can help me with?

MKS Robin E3 board

**Comment by mks-viva** [comment]
Hi! May be you need chenge it(AOS3400/CJ3400)
![image](https://user-images.githubusercontent.com/16629551/114329815-eb3aac00-9b72-11eb-90ad-a5ef96654469.png)

**Comment by danbrianwhite** [comment]
Thank you for the spec details. Will try this out.

**Comment by danbrianwhite** [comment]
Yes this fixed the issue. I happened to burn this component out on a 2nd board and the fix worked there too.
